### PR TITLE
routing-daemon: add ruby193-rubygem-rest-client dep

### PR DESCRIPTION
**Pull request by sdodson**
Fixes BZ1206013

### CODE REVIEW

**Comment by sdodson** [comment]
[test]

**Comment by sdodson** [comment]
I've verified that this shows up as a dependency for routing-daemon, it's required by other packages including node and haproxy cartridge which is why this wasn't found in test environments as they tend to be all in one installs.

```
[root@ip-10-231-177-119 ~]# yum remove ruby193-rubygem-rest-client
Loaded plugins: priorities, security
Setting up Remove Process
Resolving Dependencies
--> Running transaction check
---> Package ruby193-rubygem-rest-client.noarch 0:1.6.1-2.el6_3 will be erased
--> Processing Dependency: ruby193-rubygem(rest-client) for package: rubygem-openshift-origin-routing-daemon-0.23.1-1.git.17.e479f9a.el6.noarch
```

**Comment by sdodson** [comment]
[merge]

**Comment by brenton** [comment]
[merge]

**Pull request merged**
