### PR TITLE
[TO_STAGE] oo-accept-node: honor application names starting with 0

### PR DESCRIPTION
**Pull request by a13m**

### CODE REVIEW

**Comment by mfojtik** [comment]
[merge]

**Comment by wshearn** [comment]
[merge]

**Comment by wshearn** [comment]
[test]

**Comment by mfojtik** [comment]
[merge] again, seems like a random failure.

**Comment by mfojtik** [comment]
[merge]

**Comment by mfojtik** [comment]
[merge] (after we sacrificed a chicken)

**Pull request merged**
