### PR TITLE
Added the "--all" option to oo-admin-ctl-cartridge

### PR DESCRIPTION
**Pull request by oybed**
broker-util/oo-admin-ctl-cartridge: Added the "--all" option to allow for all information to be displayed (including the IDs/OIDs)

For more information, please see Bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1207300

### CODE REVIEW

**Comment by oybed** [comment]
@jwhonce FYI - minor update to the oo-admin-ctl-cartridge command

**Comment by jwhonce** [comment]
@abhgupta Please review this Broker utility change.  Thanks.

**Comment by oybed** [comment]
@abhgupta @jwhonce have you had a chance to look over this change? Anything you'd like me to change?

**Comment by oybed** [comment]
including @sdodson & @brenton

**Comment by jwhonce** [comment]
[test]

**Comment by abhgupta** [comment]
@oybed Was the missing --all option just an oversight? Either ways, could you please add the option description to the man page as well? If you need any help with that let me know.

Other than the comment above, LGTM.

**Comment by abhgupta** [comment]
@oybed There seem to be some unrelated commits that have been picked up. Perhaps a fetch/pull/rebase?

**Comment by oybed** [comment]
@abhgupta ahh, yes, let me fix that. Since I'm about to get on a plane, I'll fix it tomorrow. Hopefully that is ok. Sorry about that.

**Comment by oybed** [comment]
Replaced by PR #6129

**Pull request closed without merging**
