### PR TITLE
Bug 1136425

### PR DESCRIPTION
**Pull request by tiwillia**
Bug link https://bugzilla.redhat.com/show_bug.cgi?id=1136425
Disable password aging for gear users

### CODE REVIEW

**Comment by danmcp** [comment]
@jwhonce ^^

**Comment by jwhonce** [comment]
[merge]

**Comment by maxamillion** [comment]
[merge] failure unrelated

**Comment by tiwillia** [comment]
[test]

**Comment by jwhonce** [comment]
[test] again

**Comment by tiwillia** [comment]
[test]

**Comment by brenton** [comment]
[merge]

**Pull request merged**
