### PR TITLE
Bump cartridge versions for Sprint 58

### PR DESCRIPTION
**Pull request by soltysh**
//cc @bparees @danmcp

### CODE REVIEW

**Comment by bparees** [comment]
@soltysh 
1) this seems like a lot of changes, did we really touch this many carts?  what changed about DIY for example?
2) shouldn't php be an incompatible change to pick up the apc memory logic change you made?

**Comment by bparees** [comment]
@soltysh run a test/extended:gear,cartridge if you're done.

**Comment by soltysh** [comment]
@bparees from my diff it shows that in all of them links to the docs were changed (in template files).

**Comment by soltysh** [comment]
[test][extended:gear][extended:cartrdge]

**Comment by bparees** [comment]
@soltysh and php?

**Comment by soltysh** [comment]
@bparees same, links + my changes to `apc.shm_size`.

**Comment by bparees** [comment]
[merge]

**Pull request merged**
