### PR TITLE
[TO_STAGE] Various quota-related fixes

### PR DESCRIPTION
**Pull request by a13m**
This is a collection of cherry-picked changes related to the resolution of these two bugs:

https://bugzilla.redhat.com/show_bug.cgi?id=1292133
https://bugzilla.redhat.com/show_bug.cgi?id=1122084

Ideally it should be reviewed by @sallyom @Miciah and @tiwillia to check whether other commits are necessary.

### CODE REVIEW

**Comment by tiwillia** [comment]
It looks like you caught everything here. I'd rather test it before merging though. Will get something running today.

[test], even though the automated tests likely won't cover everything we need them to.

**Comment by sallyom** [comment]
@a13m I believe all the changes related to those 2 bzs are included in this PR.
 @tiwillia please test today before merging, and thanks (for setting up/testing instead of me doing it) :)

**Comment by tiwillia** [comment]
I can verify that starts and stops of at-quota gears works up until the 120% limit.

I can verify that the nodes are exposing the new `node_disk_free` and `node_total_size` facts through mcollective.

I can also verify that moving a gear using 100% quota is successful due to the use of the new quota buffer.

This LGTM

**Comment by tiwillia** [comment]
[test] again to ensure that isn't a flake

**Comment by thrasher-redhat** [comment]
We should have ultron in stage now, re[test] please!

**Comment by thrasher-redhat** [comment]
This error (addressible gem has a new version and dependency on public_suffix) is something that we just saw in master.  It involved a small change to the the Gemfile as seen here: https://github.com/openshift/rhc/commit/a271add215ff288fd709848375ac514ee85ac200

We'll likely need to pull that commit into rhc's stage.

**Comment by wshearn** [comment]
[test]

**Comment by wshearn** [comment]
[merge]

**Pull request merged**
