### PR TITLE
Bug 1244126: Allowing 4096 char limit for env variable values

### PR DESCRIPTION
**Pull request by abhgupta**

### CODE REVIEW

**Comment by abhgupta** [comment]
@tiwillia please review

**Comment by tiwillia** [comment]
@abhgupta LGTM, you'll have to [merge] though.

**Comment by tiwillia** [comment]
[merge]

**Comment by abhgupta** [comment]
re-[merge] to debug the test failures

**Comment by lostfictions** [comment]
Hey there, is this fix deployed on openshift.com? I'm trying to set an environment variable with `rhc env set`, but it's still telling me `Value must be 512 characters or less.`

**Pull request merged**
