### PR TITLE
BZ1225327: Setting apc.stat on by default

### PR DESCRIPTION
**Pull request by jhadvig**

### CODE REVIEW

**Comment by jhadvig** [comment]
[test][extended:cartridge]

**Comment by mfojtik** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by mfojtik** [comment]
Just fyi, we tested this change manually and everything worked with php....
So i don't quite understand the failure in merge test :(

**Comment by jhadvig** [comment]
@bparees as @mfojtik said, we tested it today manually on devenv and everything worked without any problem ... :-/

**Pull request merged**
