### PR TITLE
RHBZ1198777: Scale inodes by 80k per GB in example configs

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by danmcp** [comment]
@sdodson Where is this request coming from?  We use these values in production.

**Comment by sdodson** [comment]
@danmcp https://bugzilla.redhat.com/show_bug.cgi?id=1198777 these are just the example configuration files however, we're automatically copying those into use in online?

Here's a related bug where it looks like online switched to 80k/GB long ago.
https://bugzilla.redhat.com/show_bug.cgi?id=1031112

**Comment by danmcp** [comment]
@sdodson Sorry I got mixed up.  These are not the examples I thought they were :)  And I totally missed the quota_blocks was already different.

**Comment by danmcp** [comment]
[merge]

**Pull request merged**
