### PR TITLE
Fix inconsistent return exit code for various commands

### PR DESCRIPTION
**Pull request by dinhxuanvu**
The exit code 255 should be returned if commands with missing or
incorrect required parameters are executed instead of exit code 0.

Signed-off-by: Vu Dinh vdinh@redhat.com

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
@tiwillia Have you seen the issue anywhere else? I found only one so far.

**Comment by dinhxuanvu** [comment]
[test]

**Comment by tiwillia** [comment]
These changes LGTM :+1:

**Comment by Miciah** [comment]
Please [merge]!

**Pull request merged**
