### PR TITLE
Bug 1261156 - Fix oo-admin-xx help command returns an exitcode 255 instead of 0

### PR DESCRIPTION
**Pull request by dinhxuanvu**
Currently, many oo commands with help option return an exitcode 255 instead of 0.
This commit will specifically return 0 for --help option and 255 for incorrect
options.

Bug 1261156
Link https://bugzilla.redhat.com/show_bug.cgi?id=1261156

Signed-off-by: Vu Dinh vdinh@redhat.com

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
@tiwillia @Miciah [test]

**Comment by dinhxuanvu** [comment]
@Miciah @tiwillia This is a low-priority PR but would like to have it reviewed and merged to clear up the log :D. Thanks.

**Comment by tiwillia** [comment]
@dinhxuanvu The changes you've made look good. I ran through a loop of every oo-command and ran them with --help to determine which still did not report a '0' exit code. Those that did not report '0' did not support a --help, -h, or help argument, so the non-zero code is expected.

The oo-gear-registry command was the only command that has a --help option and results in a non-zero exit code. This appears to be due to an error which results in the non-zero exit code:
```
# oo-gear-registry --help
  NAME:

    ["OpenShift Gear Registry Access"]

  DESCRIPTION:

    ["Access utility for gear registry"]

  COMMANDS:
	
    help                 Display global or [command] help documentation.	

  GLOBAL OPTIONS:
	
    -h, --help 
        Display help documentation
	
    -v, --version 
        Display version information
	
    -t, --trace 
        Display backtrace when an error occurs
	
/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-node-1.38.4/lib/openshift-origin-node/model/application_container.rb:141:in `from_uuid': container_uuid is required! (ArgumentError)
	from /usr/bin/oo-gear-registry:35:in `<main>'
```
We should probably fix that in another PR, but its out-of-scope for this one.

LGTM. [merge]

**Comment by dinhxuanvu** [comment]
@tiwillia Would you mind re-merging this as the net-ssh PR is already merged.

**Comment by tiwillia** [comment]
[merge]

**Pull request merged**
