### PR TITLE
Add "-e" option to python cartridge to stop deploy process when it failed to install packages

### PR DESCRIPTION
**Pull request by nak3**

### CODE REVIEW

**Comment by nak3** [comment]
This PR fixes https://bugzilla.redhat.com/show_bug.cgi?id=1303796 , although this `-e` option has been removed by https://github.com/openshift/origin-server/pull/3542 purposely.

**Comment by dinhxuanvu** [comment]
[test]

**Comment by Miciah** [comment]
[test] [extended:cartridge]

**Comment by nak3** [comment]
@dinhxuanvu @Miciah  I can't open [test results](https://ci.dev.openshift.redhat.com/jenkins/job/test_pull_requests/9177/). But I don't think this change effects something. Could you please re-run test?

**Comment by tiwillia** [comment]
@nak3 looks like all the tests passed, but the acceptance script that is run at the end of testing failed:
```
E, [2016-02-02T11:49:15.809892 #4975] ERROR -- : 
SSH command ssh 2> /dev/null -t -n -o TCPKeepAlive=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PasswordAuthentication=no -i /var/lib/jenkins/.ssh/devenv.pem root@ec2-52-90-45-1.compute-1.amazonaws.com '/usr/bin/rhc-accept-devenv 2>&1' failed to ec2-52-90-45-1.compute-1.amazonaws.com with exit_code: 2  and output: FAIL: directory 56b0d788ff279cc97a00000a doesn't have a cartridge directory
FAIL: directory 56b0d788ff279cc97a00000a/.env doesn't have OPENSHIFT_PRIMARY_CARTRIDGE_DIR
2 ERRORS
Accept Node Output: , try 1 of 1
Devenv Acceptance Output = FAIL: directory 56b0d788ff279cc97a00000a doesn't have a cartridge directory
FAIL: directory 56b0d788ff279cc97a00000a/.env doesn't have OPENSHIFT_PRIMARY_CARTRIDGE_DIR
```

Lets re-[test] and see if this failure is spurious or not.

**Comment by nak3** [comment]
Thank you @tiwillia! Hmm... test failed again and I can't see the result by `Details` button.

**Comment by dinhxuanvu** [comment]
@nak3 Are you working remotely? I'm a bit surprised that you are unable to access Jenkins.
Also, the libra_ami is failed recently and it's been in process of rebuilding so please hold before doing another test/merge. Thanks.

**Comment by dinhxuanvu** [comment]
Ready for re-[test]

**Comment by tiwillia** [comment]
@nak3 just a quick explanation - the latest test failures were unrelated. They were due to some spurious failures in the build of our openshift image we use for testing.

**Comment by dinhxuanvu** [comment]
@nak3 Hi. So we have a plan in place for this issue. Since the "-e" was removed due to regression issue, we can't simply merge this PR yet. Instead, we will create an fork image with this specific change and run it pass QA regression suite. Then, based on the result of that run, we will decide what will happen next. I hope this makes sense. This may take a bit of time since QE team is in holiday this week. Thanks!

**Comment by tiwillia** [comment]
Regression testing complete. Commencing [merge] sequence.

**Pull request merged**
