### PR TITLE
fix extended tests RestClient.delete

### PR DESCRIPTION
**Pull request by sallyom**

### CODE REVIEW

**Comment by sallyom** [comment]
@Miciah @tiwillia woot woot! 
[test][extended:cartridge,gear]

**Comment by tiwillia** [comment]
Ah, nice job! This LGTM.

Do we want to also do the extended node test or is there a reason it was excluded?

**Comment by sallyom** [comment]
[test] [extended:node,broker,rhc,site,cartridge,gear]  pleeeeese!

**Comment by sallyom** [comment]
[test] [extended:node,broker,rhc,cartridge,gear]  pleeeeese!

**Comment by sallyom** [comment]
[test] [extended:node,broker,rhc,cartridge,gear] pleeeeese!

**Comment by thrasher-redhat** [comment]
Lots of weird tests in that last attempt.  Look like most of them timed out for some reason.  May want to test again.

**Comment by sallyom** [comment]
[test] [extended:node,broker,rhc,cartridge,gear] pleeeeese!

**Comment by sallyom** [comment]
[test] [extended:node,broker,rhc,cartridge,gear] pleeeeese (I'm impatient)!

**Comment by sallyom** [comment]
@tiwillia just the site extended tests are failing...I didn't mean to run the extended:site, bc of the known failures.  Should be all set other than that.

**Comment by dinhxuanvu** [comment]
[test] [extended:node,broker,rhc,cartridge,gear]

**Comment by dinhxuanvu** [comment]
[test] [extended:node,broker,rhc,cartridge,gear] please!

**Comment by sallyom** [comment]
[test] [extended:node,broker,rhc,cartridge,gear] please!

**Comment by dinhxuanvu** [comment]
Finally, it has passed. @Miciah Any final thoughts? A merge blessing :100:

**Comment by Miciah** [comment]
Lovely jubbly! openshift-bot, please [merge]!

**Comment by Miciah** [comment]
Thanks!

**Pull request merged**
