### PR TITLE
Delete unused variables in Upgrader

### PR DESCRIPTION
**Pull request by Miciah**
[test]

### CODE REVIEW

**Comment by Miciah** [comment]
Test failure looks unrelated to the changes in the PR:

```
  Installing : drupal6-openshift-features-forums-1.9.1-1.git.0.30511a5.   83/84 
E, [2015-09-29T19:18:36.163127 #9780] ERROR -- : 
SSH command to ec2-54-85-43-124.compute-1.amazonaws.com timed out (timeout = 7200)
```

[test] again.

**Comment by Miciah** [comment]
Weird—it timed out in the same place:

```
  Installing : drupal6-openshift-features-forums-1.9.1-1.git.0.30511a5.   83/84 
E, [2015-10-01T15:52:17.072713 #20403] ERROR -- : 
SSH command to ec2-52-23-218-102.compute-1.amazonaws.com timed out (timeout = 7200)
```

[test] again.

**Comment by Miciah** [comment]
Failed on the following, which was fixed by <https://www.github.com/openshift/rhc/pull/703>:

```
Bundler could not find compatible versions for gem "net-ssh":
  In Gemfile:
    rhc (>= 0) ruby depends on
      net-ssh (< 2.9.3, >= 2.0.11) ruby

    rhc (>= 0) ruby depends on
      net-ssh (3.0.1)
```

[test] again.

**Comment by Miciah** [comment]
I will tag this PR to have the gear extended tests run on it once #6291 is merged.

**Comment by Miciah** [comment]
[test] [extended:gear]

**Comment by Miciah** [comment]
@tiwillia, I have this way old cleanup PR.  Looks like the last test run succeeded—think it's worth merging?

**Comment by tiwillia** [comment]
I'm wary to merge anything we don't explicitly need at this point, but this PR is rather harmless.

Lets [merge] it.

**Pull request merged**
