### PR TITLE
Bug 1232907 - Only unidle on start by user

### PR DESCRIPTION
**Pull request by jwhonce**
- See also: https://bugzilla.redhat.com/show_bug.cgi?id=966790

### CODE REVIEW

**Comment by jwhonce** [comment]
@a13m @ironcladlou Please review.  I'm not sure why we didn't have user_initiated set before...

**Comment by ironcladlou** [comment]
LGTM, seems like this script (an admin/systems script) should honor locks via user_initiated=false.

**Comment by jwhonce** [comment]
[merge]

**Comment by jwhonce** [comment]
[merge]again

**Pull request merged**
