### PR TITLE
Card devexp_483 - Obsoleting 10gen cartridge

### PR DESCRIPTION
**Pull request by soltysh**
//fyi @danmcp

### CODE REVIEW

**Comment by soltysh** [comment]
[test][extended:cartridge]

**Comment by danmcp** [comment]
@soltysh You're going to need to change the corresponding test cases as well.  Plus make sure to find the last release ticket we obsoleted a cart (metrics-0.1 was on of them) and add the details to the current release ticket.

**Comment by soltysh** [comment]
@danmcp I've removed the test cases, although they were already commented out, I'm guessing after reworking the 10gen cart the last time and suggestion from mongodb cart. I've also already spoke with @maxamillion on where and what to put in the release ticket. Thanks :smile:

**Comment by soltysh** [comment]
@danmcp are you ok with merging it now?

**Comment by danmcp** [comment]
[merge]

@soltysh btw if you use origin_devexp_483 in the title or a comment the bot will add a message to the card when it merges.

**Comment by soltysh** [comment]
>@soltysh btw if you use origin_devexp_483 in the title or a comment the bot will add a message to the card when it merges.

Aha, I need to update my git commit templates since I have devexp_<no> there, I knew it used to work. Thanks Dan :smile:

**Pull request merged**
