### PR TITLE
rhc-list-ports: Fix output of scaled gears

### PR DESCRIPTION
**Pull request by Miciah**
Read the list of scaled gears from the correct location.

Commit 487e6e238d1d4ce68fd7df852f50ed5c161cf4ea replaced `haproxy/conf/gear-registry.db` with `gear-registry/gear-registry.json`.

### CODE REVIEW

**Comment by danmcp** [comment]
@Miciah @jwhonce @ncdc Ready for merge?

**Comment by ncdc** [comment]
@smarterclayton @fabianofranz does anything use these SCALE lines?

**Comment by fabianofranz** [comment]
@ncdc not on `rhc`.

**Comment by smarterclayton** [comment]
Don't we use the rhc-list-ports output to determine what to port forward to?  Whether something is scalable affects that decision.

**Comment by ncdc** [comment]
@smarterclayton we haven't found anyplace where SCALE is used so far

**Comment by Miciah** [comment]
I'll make a new PR today to delete the code.

**Comment by Miciah** [comment]
Closing in favour of PR #6049.

**Pull request closed without merging**
