### PR TITLE
Removing oo-broker prefixes for admin commands

### PR DESCRIPTION
**Pull request by abhgupta**

### CODE REVIEW

**Comment by akostadinov** [comment]
why is the change? can such changes be synced with QE first in the future?

**Comment by abhgupta** [comment]
@akostadinov point taken on informing QE ahead of time.

**Comment by akostadinov** [comment]
Thank you. In the beginning I thought change is effective immediately.

**Comment by abhgupta** [comment]
@akostadinov It is effective immediately. It affects the devenv as well as origin (upstream) broker. There is nothing that changes for Online.

**Comment by akostadinov** [comment]
strange, @danmcp wrote it will be effective sprint 103... anyway

**Comment by abhgupta** [comment]
@akostadinov not sure about that - but its all there now.

**Comment by danmcp** [comment]
@akostadinov The end of sprint 103 is when it will end up in production.  Which means we have 4 more weeks to get all the testing lined up.

**Pull request merged**
