### PR TITLE
[TO_STAGE] Fix render error

### PR DESCRIPTION
**Pull request by joelsmith**

### CODE REVIEW

**Comment by wshearn** [comment]
[merge]

**Comment by wshearn** [comment]
[merge] failure is not related.

**Comment by joelsmith** [comment]
[test]

**Comment by dak1n1** [comment]
ok to test

**Comment by dak1n1** [comment]
[test]

**Comment by dak1n1** [comment]
[test]

**Comment by wshearn** [comment]
[merge]

**Pull request closed without merging**
