### PR TITLE
Bug 1152524 Check MongoDB hosts connectivty prior to loading broker rails environment

### PR DESCRIPTION
**Pull request by tiwillia**
Bug 1152524
https://bugzilla.redhat.com/show_bug.cgi?id=1152524

oo-accept-broker: Check for connectivity with MongoDB hosts prior to attempting to load the broker's rails environment. Failing to do so previously resulted in oo-accept-broker waiting ~7 minutes for the broker database connection attempts to finally timeout.

### CODE REVIEW

**Comment by tiwillia** [comment]
[test]

**Comment by tiwillia** [comment]
@sosiouxme or @detiber  could one of you review?

**Comment by sosiouxme** [comment]
LGTM [merge]

**Comment by tiwillia** [comment]
re-[merge]. Merge failures appear to be unrelated (time outs)

**Comment by tiwillia** [comment]
re-[merge] again, the new test failures appear to be caused by the mongo database never becoming available. No tests were actually run, since the broker never started.

**Pull request merged**
