### PR TITLE
update Dockerfile

### PR DESCRIPTION
**Pull request by sallyom**
Signed-off-by: Sally O'Malley somalley@redhat.com

### CODE REVIEW

**Comment by sallyom** [comment]
not sure if anyone uses this Dockerfile but since it was broken I updated it to build

**Comment by dinhxuanvu** [comment]
[test]

**Comment by tiwillia** [comment]
Just re[test]-ing this to see if all PRs are experiencing the same test failures in jenkins...

**Comment by bparees** [comment]
i'm not sure the history behind this, i think maybe @jwforres did the docker-ization of v2 so she might know?

**Comment by tiwillia** [comment]
@bparees Thanks, I'm pretty sure we aren't pursuing this PR any more. I just needed another PR to test to verify that tests are failing for all PRs.

@sallyom can this be closed?

**Comment by sallyom** [comment]
@tiwillia  I meant to close this!

**Pull request closed without merging**
