### PR TITLE
fixup from PR 6342, add apache-vhost plugin ssl-crt-chain-path refs back

### PR DESCRIPTION
**Pull request by sallyom**
(was removed with PR #6342)

### CODE REVIEW

**Comment by sallyom** [comment]
@Miciah please review

**Comment by tiwillia** [comment]
[test]

**Comment by sallyom** [comment]
@Miciah, I don't think we need https://github.com/openshift/origin-server/commit/62ef0ec522b0fe26050d7c375ee5098c060b1d5c#diff-b0577d090311ee97b05ba0b6d4e55858L388 ?  I believe this is now the same as 'ssl_certificate_file = ssl_certificate_path(server_alias)' here.  'I believe' != 'I am 100% positive'

**Comment by sallyom** [comment]
@Miciah, good?

**Comment by Miciah** [comment]
Spiffin'!

**Comment by Miciah** [comment]
Please [merge]!

**Pull request merged**
