### PR TITLE
Add authorization header in node-proxy.

### PR DESCRIPTION
**Pull request by PatrykGala**
Add a authorization header in websocket handshake.
[issue#6443.](https://github.com/openshift/origin-server/issues/6443)

### CODE REVIEW

**Comment by PatrykGala** [comment]
[test]

**Comment by PatrykGala** [comment]
@tiwillia  @Miciah please review  and merge.

**Review by Miciah — APPROVED** [review]

**Comment by Miciah** [comment]
openshift-bot, please [test]!

**Comment by PatrykGala** [comment]
@Miciah could you merge?

**Comment by tiwillia** [comment]
[merge] please!

**Pull request merged**
