### PR TITLE
Bug 1181916:  max_prepared_transactions setting

### PR DESCRIPTION
**Pull request by nak3**
Fix for bz1181916.
Please refer to [bz1181916](https://bugzilla.redhat.com/show_bug.cgi?id=1181916)

### CODE REVIEW

**Comment by nak3** [comment]
Here is my test steps:

]# rhc app-create -t ruby-1.9 -a bz1181916
]# rhc cartridge add postgresql-9.2 -a bz1181916
]# rhc ssh bz1181916 grep max_prepared_transactions ./postgresql/data/postgresql.conf
`max_prepared_transactions = 0`
]# rhc env-set OPENSHIFT_POSTGRESQL_MAX_PREPARED_TRANSACTIONS="100" -a bz1181916
]# rhc cartridge restart postgresql-9.2 -a bz1181916
]# rhc ssh bz1181916 grep max_prepared_transactions ./postgresql/data/postgresql.conf
`max_prepared_transactions = 100`

**Comment by brenton** [comment]
@mfojtik, Are you OK with this?

I guess the patch could be more succinct it we didn't have the check to ensure it's greater than 0.  If the error from postgres is clear to the user I tend to preferring failing fast and let them see the error instead of silently working around their mistake by inserting a 0.  Maybe they have a bug in their script that sets the value and they should know about it.

**Comment by mfojtik** [comment]
@brenton as long as that ENV var is documented I'm OK ;-)

**Comment by brenton** [comment]
@mfojtik, We'll make sure that happens as part of the bugzilla.  Feel free to slap a merge tag on this PR if it's OK to merge upstream now.  It isn't required for the upcoming Online release.  That said, we'll have QE test it in OSE as well as Online.

**Comment by mfojtik** [comment]
[merge]

**Comment by nak3** [comment]
@mfojtik @brenton

Sorry for my late comment. I read brenton's first comment just now. And I agree with him.
We should change like this.

~~~
#------------------------------------------------------------------------------
# PREAPRED TRANSACTIONS
#------------------------------------------------------------------------------
max_prepared_transactions = <%= ENV['OPENSHIFT_POSTGRESQL_MAX_PREPARED_TRANSACTIONS'] || 0 %>
~~~

Because
1. It is very simple.
2. If user set invalid value like OPENSHIFT_POSTGRESQL_MAX_PREPARED_TRANSACTIONS="a", the cartridge will be stopped during the restart without inserting the valid "0" but unexpected value.
(although brenton has already said it...)

Anyway should I re-submit PR or leave current merged patch?

**Comment by brenton** [comment]
@nak3  You can submit another commit to this pull request and jenkins will postpone the merge job.

**Comment by nak3** [comment]
Updated my patch and here is my test steps

]# rhc app-create -t ruby-1.9 -a bz1181916updated
]# rhc cartridge add postgresql-9.2 -a bz1181916updated
]# rhc ssh bz1181916updated grep max_prepared_transactions ./postgresql/data/postgresql.conf
`max_prepared_transactions = 0`
]# rhc env-set OPENSHIFT_POSTGRESQL_MAX_PREPARED_TRANSACTIONS="100" -a bz1181916updated
]# rhc cartridge restart postgresql-9.2 -a bz1181916updated
]# rhc ssh bz1181916updated grep max_prepared_transactions ./postgresql/data/postgresql.conf
`max_prepared_transactions = 100`
]# rhc env-set OPENSHIFT_POSTGRESQL_MAX_PREPARED_TRANSACTIONS="-1" -a bz1181916updated
]# rhc cartridge restart postgresql-9.2 -a bz1181916updatedRestarting postgresql-9.2 ...
`Failed to execute: 'control restart' for`
`/var/lib/openshift/54b7d651e659c528e5000002/postgresql`

**Comment by brenton** [comment]
Thanks @nak3, I'll let Michal weigh in on which approach he prefers and then submit this for merging.  I don't feel too strongly about failing fast in this scenario because looking at this cartridge now I see we have lots of precendence for covering up user mistakes without telling them.  @mfojtik, whichever approach you prefer is fine with me.

**Comment by brenton** [comment]
@mfojtik, I guess I was mistaken about how our github bot works.  I was thinking that if another commit was added to the PR that you would have to type merge again.  Anyway, if you prefer we could just as easily revert the last commit.

**Pull request merged**
