### PR TITLE
Adding Logic to allow for mvm mirror to be overwritten

### PR DESCRIPTION
**Pull request by sferich888**
There is no way to override the mirror, if you are openshift online.

### CODE REVIEW

**Comment by tiwillia** [comment]
LGTM, but I am no maven expert. @bparees could you review? Any problems with allowing users to overwrite the `OPENSHIFT_MAVEN_MIRROR` variable?

**Comment by bparees** [comment]
seems ok to me, can you make the same change in our jbossAS and ews cartridges?  (you can do it all in the same commit+PR)

**Comment by a13m** [comment]
@sferich888 , can we talk about the use case here?  We populate a maven mirror and make people use it for a reason.  Bypassing it will typically cost us more and make their performance worse.  Why do we want to allow that?

**Comment by sferich888** [comment]
@a13m I agree allowing for this might be a bad idea. However what if there are outages with the mirror (where customers want a workaround). With out this we have to wait on OpenShift Online to fix the mirrors. This PR is simply to give support a workaround (temporary) for those situations.

**Comment by sferich888** [comment]
All, I am going to close this because of @a13m suggestions. Modifying the correct settings.xml file to point to a different registry is a workaround to these situations. 

All this would do is introduce another layer to the issue.

**Pull request closed without merging**
