### PR TITLE
Removing unnecessary quotes added to the description

### PR DESCRIPTION
**Pull request by abhgupta**

### CODE REVIEW

**Comment by bparees** [comment]
lgtm [merge]

**Comment by abhgupta** [comment]
Apparently the quotes are required since there is a 'colon' within the description.

**Comment by Miciah** [comment]
Alternatively, we could delete the colon.  I've known at least one English professor who would argue that our use of the colon here is grammatically incorrect.

**Comment by abhgupta** [comment]
@Miciah We can consider doing that the next time we bump up the cartridge version number.

**Pull request closed without merging**
