### PR TITLE
teste

### PR DESCRIPTION
**Pull request by luispimenta**

### CODE REVIEW

**Comment by tiwillia** [comment]
Was this purposefully submitted? Could you explain your reasoning for these changes if you intend to get this code into openshift/origin-server?

**Comment by luispimenta** [comment]
I am trying to install via github phpmyadmin, but I can not!
Can you help me?

**Comment by tiwillia** [comment]
@luispimenta The `Source-url` directive in the manifest needs to point to either a git repo (not a directory in a git repo), an archive file, or a local file. See the [Cartridge Specification Guide](https://access.redhat.com/documentation/en-US/OpenShift_Online/2.0/html-single/Cartridge_Specification_Guide/index.html#Source-Url_Element1) for more information.

So, you will need to do one of the following:

1) Create a git repository on github specifically for the phpmyadmin cartridge and include only the files from `cartridges/openshift-origin-cartridge-phpmyadmin` in the repository.
2) Archive, using tar or zip, the cartridge files from `cartridges/openshift-origin-cartridge-phpmyadmin` and upload them somewhere public.
3) Copy the files to a local directory on your node

You will need to modify the manifest to include the correct URL in the `Source-url` directive. Alternatively, you can use the [cartridge-reflector](https://github.com/smarterclayton/cartridge-reflector) to re-write the manifest for you when you download and use the cartridge.

**Comment by tiwillia** [comment]
I have not heard back from you yet. If you are having any further issues, please feel free to seek assistance on http://stackoverflow.com/tags/openshift or on the #openshift irc channel on freenode.

Additionally, you can send an email to the users@lists.openshift.redhat.com email list for further assistance.

@abhgupta we can close this.

**Pull request closed without merging**
