### PR TITLE
[WIP] Bug 1194029 - add multiple app aliases in a single httpd reload

### PR DESCRIPTION
**Pull request by a13m**

### CODE REVIEW

**Comment by a13m** [comment]
[test]

**Comment by thrasher-redhat** [comment]
Openshift-bot, please [test]!

**Comment by thrasher-redhat** [comment]
Looks like an unrelated instance failure - please re[test]

**Comment by thrasher-redhat** [comment]
Another instance failure while installing nodejs.  Going to try again.  [test]

**Comment by a13m** [comment]
I have done some testing of this, and it's not threaded all the way through yet.  oo-admin-move is still making individual mcollective calls for each alias, so it doesn't matter yet what the mco client side looks like.   I'm going to work on this a bit more

**Review by Miciah — APPROVED** [review]

**Comment by thrasher-redhat** [comment]
As an FYI, jenkins testing currently blocked due to nodejs dependency error - working on a fix here: https://github.com/openshift/li/pull/3147

**Comment by thrasher-redhat** [comment]
Looks like we may have figured out the nodejs error - re[test] please!

**Comment by Miciah** [comment]
Now Yum is failing with the following error:
```
Error: Package: 1:rubygem-passenger-3.0.21-12.el6oso.x86_64 (devenv)
           Requires: rubygem(daemon_controller) >= 1.0.0
           Available: rubygem-daemon_controller-0.2.5-3.el6.noarch (devenv)
               rubygem(daemon_controller) = 0.2.5
```

**Comment by thrasher-redhat** [comment]
Ummmmmm.  The daemon_controller gem was at version 0.2.5 back in 2010...

https://rubygems.org/gems/daemon_controller/versions

**Comment by Miciah** [comment]
Please [test] again!

**Comment by thrasher-redhat** [comment]
Is it back?  Can we [test] again?

**Comment by thrasher-redhat** [comment]
Looks like the installation of rubygem-daemon_controller was a success!  But something else caused `ERROR - instance is not valid`.  Going to re[test].

**Comment by thrasher-redhat** [comment]
Untying this from another PR to verify that this works alone.  Once this test passes, it looks good to me.

One last re[test] please!

**Comment by Miciah** [comment]
openshift-bot, please [test][extended:node,gear]!

**Comment by Miciah** [comment]
Lovely jubbly! openshift-bot, please [merge]!

**Pull request merged**
