### PR TITLE
Make console functional tests less random

### PR DESCRIPTION
**Pull request by Miciah**
#### Make console functional tests less random

Replace random selection of application types for console functional tests with arbitrary selections.  This change should fix test failures that result when the tests randomly select invalid application types from the OpenShift Hub.
#### Delete deadcode in node functional test

Delete `JbossPlugin#jboss_name`, which has been deadcode since commit 356a189fa3991bd0e1b50d23f7f75e775d0f2edd.
## 

[test]

### CODE REVIEW

**Comment by Miciah** [comment]
Site Check Miscellaneous 2 failed the first time through with the following:

```
  1) Failure:
test_should_retrieve_application_details_with_one_alias(ApplicationsControllerTest) [/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.35.1/test/functional/applications_controller_test.rb:242]:
</normal/> expected but was
<"We appear to be having technical difficulties">.
```

This failure is not like the ones this PR fixes, and Site Check Miscellaneous 2 succeeded on retry.

@abhgupta, does this look OK?

**Comment by abhgupta** [comment]
LGTM - waiting for the tests to pass for merge.

**Comment by abhgupta** [comment]
@Miciah what is the status on this?

**Comment by Miciah** [comment]
These failures are new to me, and it is not obvious that the changes in this PR could be causing them:
```
  1) Failure:
test_cartridge_scale_parameters_can_be_changed(RestApiCartridgeTest) [/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.35.1/test/integration/rest_api/cartridge_test.rb:47]:
Unable to set scales_from/to to 1: ["Failed to get cartridge 'ruby-1.8' from ruby in gear 55f9d1215b2e66d18f000101: '' is not a legal cartridge identifier", "Unable to complete the requested operation due to: An invalid exit code (1) was returned from the server ip-172-18-10-97.  This indicates an unexpected problem during the execution of your request.\nReference ID: e4c85e5ce8a007c7061ebaa23db8c269"]

  2) Failure:
test_allows_fixed_scale_range(ScalingControllerTest) [/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.35.1/test/functional/scaling_controller_test.rb:85]:
Expected response to be a <:redirect>, but was <200>

  3) Failure:
test_allows_unlimited_scale_range(ScalingControllerTest) [/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.35.1/test/functional/scaling_controller_test.rb:91]:
Expected response to be a <:redirect>, but was <200>

  4) Failure:
test_flips_scale_range_if_necessary(ScalingControllerTest) [/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.35.1/test/functional/scaling_controller_test.rb:97]:
Expected response to be a <:redirect>, but was <200>

  5) Failure:
test_updates_scale_range(ScalingControllerTest) [/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.35.1/test/functional/scaling_controller_test.rb:79]:
Expected response to be a <:redirect>, but was <200>
```
and
```
  1) Failure:
test_cartridge_scale_parameters_can_be_changed(RestApiCartridgeTest) [/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.35.1/test/integration/rest_api/cartridge_test.rb:47]:
Unable to set scales_from/to to 2: ["Unable to perform action on app object. Another operation is already running."]

  2) Failure:
test_allows_fixed_scale_range(ScalingControllerTest) [/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.35.1/test/functional/scaling_controller_test.rb:85]:
Expected response to be a <:redirect>, but was <200>

  3) Failure:
test_allows_unlimited_scale_range(ScalingControllerTest) [/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.35.1/test/functional/scaling_controller_test.rb:91]:
Expected response to be a <:redirect>, but was <200>

  4) Failure:
test_flips_scale_range_if_necessary(ScalingControllerTest) [/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.35.1/test/functional/scaling_controller_test.rb:97]:
Expected response to be a <:redirect>, but was <200>

  5) Failure:
test_updates_scale_range(ScalingControllerTest) [/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.35.1/test/functional/scaling_controller_test.rb:79]:
Expected response to be a <:redirect>, but was <200>
```
I'll investigate further if I see the same failures in a second test run.  [test] again.

**Comment by Miciah** [comment]
But for the test failures, I would be happy to merge this PR.

**Comment by Miciah** [comment]
Tests passed, although there was an intermittent failure in Site Check Miscellaneous 2 Tests:
```
  1) Failure:
test_should_retrieve_application_details_with_one_alias(ApplicationsControllerTest) [/opt/rh/ruby193/root/usr/share/gems/gems/openshift-origin-console-1.35.3/test/functional/applications_controller_test.rb:242]:
</normal/> expected but was
<"We appear to be having technical difficulties">.
```
That failure looks like a hiccup that is not likely caused by this change, so let's [merge].

**Pull request merged**
