### PR TITLE
Bug 1283380 - A warning "'webkitIndexedDB' is deprecated" in console with Chrome

### PR DESCRIPTION
**Pull request by dinhxuanvu**
OpenShift Online console currently uses Modernizr JS library 1.7 which is
outdated and it causes a warning regarding deprecated webkitIndexedDB method
in Chrome browser.

This commit upgrades the modernizr library from 1.7 to 2.6.2 which will
eliminate the warning.

Bug 1283380
Link https://bugzilla.redhat.com/show_bug.cgi?id=1283380

Signed-off-by: Vu Dinh vdinh@redhat.com

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
@tiwillia @Miciah Got a thumb-up from QA! [test]

**Comment by dinhxuanvu** [comment]
@a13m Would you mind taking a look at this change. Thanks!

**Comment by dinhxuanvu** [comment]
@tiwillia Will check with QE again to verify if they have done regression test on this or not. For now, please do not merge. Thanks.

**Comment by dinhxuanvu** [comment]
@tiwillia QE has done regression + acceptance testing on the issue and verified it's good to do. Also, double-check with @jwforres and she has given a thumb-up. Unless, you have any further questions, please merge if you will. Thanks.

**Comment by tiwillia** [comment]
@dinhxuanvu thank you very much for doing the needful and getting this tested. Good job on this.

[merge]

**Pull request merged**
