### PR TITLE
Cartridge version bump for Sprint 56

### PR DESCRIPTION
**Pull request by jhadvig**

### CODE REVIEW

**Comment by jhadvig** [comment]
[test]

**Comment by mfojtik** [comment]
LGTM @danmcp could you second on this?

**Comment by mfojtik** [comment]
@danmcp there is no 'li' PR as there were no changes to cartridges there

**Comment by bparees** [comment]
@jhadvig I cherry picked this to another PR here https://github.com/openshift/origin-server/pull/6045

we weren't sure if you'd have a chance to finish it up before stage cut.

I also made php compat per @danmcp

**Pull request closed without merging**
