### PR TITLE
Bug 1192557 - Fixed creating application using --from-code=empty when database cartridge is also specified.

### PR DESCRIPTION
**Pull request by soltysh**
[Bug 1192557](https://bugzilla.redhat.com/show_bug.cgi?id=1192557)

//fyi @bparees @cianclarke

### CODE REVIEW

**Comment by soltysh** [comment]
[test][extended:node]

**Comment by bparees** [comment]
lgtm. [merge]

**Comment by bparees** [comment]
[test][extended:cartridge,gear]

**Comment by bparees** [comment]
[merge]

**Pull request merged**
