### PR TITLE
oo-accept-node: check_quotas: cope with loop mount

### PR DESCRIPTION
**Pull request by Miciah**
#### `oo-accept-node`: Add and use `do_warn`

Define and use the `do_warn` method.
#### `oo-accept-node`: `check_quotas`: cope with loop mount

Modify `oo-accept-node`'s quota check to check whether the mount is using a loop device mount and, if so, check the quota on the loop device.  In addition, print a warning that using a loop mount may impact performance negatively.

This commit fixes bug 1265811.

https://bugzilla.redhat.com/show_bug.cgi?id=1265811
#### `oo-accept-node`: `check-quotas`: simplify code

Simplify the logic in `oo-accept-node`'s `check_quotas` function to run the `df` command and parse its output only once.
## 

@sferich888, @tiwillia

I could not resist making the gratuitous cleanup, but I can drop it if you think I ought.

### CODE REVIEW

**Comment by Miciah** [comment]
Please [test]!

**Comment by tiwillia** [comment]
@Miciah do we need both commits here, or can we squash them into one?

This LGTM otherwise.

**Comment by Miciah** [comment]
I'd rather keep them in separate commits, or even drop the simplification, rather than squash, which I believe would make the changes more difficult to read.

**Comment by sferich888** [comment]
Is it really wise to support loop devices for the /var/lib/openshift directory. Wouldn't this cause performance issues if allowed?

**Comment by Miciah** [comment]
There probably generally is a better solution to any problem that someone solves using loop devices.

If an administrator does use a loop device for `/var/lib/openshift/`, `oo-accept-node` currently prints a bogus failure.  This PR enables `oo-accept-node` to function properly.  An alternative would be to make `oo-accept-node` clearly and explicitly fail (or print a warning) if `/var/lib/openshift/` is on a loop device, with an accurate error message.  Would that alternative be better?

**Comment by sferich888** [comment]
I propos allowing for this and posting a clear warning

**Comment by Miciah** [comment]
I have updated the test to print a warning if `/var/lib/openshift/` is a loop mount:

```ruby
      do_warn "#{oo_mount} is a loop mount (loop device: #{oo_device}).  Using a loop mount may reduce performance." 
```

@tiwillia, does this look good to you?

**Comment by tiwillia** [comment]
@Miciah :+1: LGTM

Shall I merge?

**Comment by Miciah** [comment]
Thanks! I do the honours...

openshift-bot, please [merge]!

**Pull request merged**
